| create_table_statement                                                                                                                                                                                                                                       |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| CREATE TABLE application_documents (is_verified boolean NOT NULL, application_id uuid NOT NULL, document_type text NOT NULL, file_path text NOT NULL, uploaded_at timestamp with time zone NOT NULL, id bigint NOT NULL);                                    |
| CREATE TABLE applications (claimed_at timestamp with time zone, status text NOT NULL, student_id uuid NOT NULL, claim_status text, ticket_number text, remarks text, applied_at timestamp with time zone NOT NULL, id uuid NOT NULL);                        |
| CREATE TABLE assistance_programs (is_open boolean NOT NULL, semester text NOT NULL, academic_year text NOT NULL, description text, created_at timestamp with time zone NOT NULL, title text NOT NULL, id bigint NOT NULL);                                   |
| CREATE TABLE barangays (id bigint NOT NULL, name text NOT NULL, created_at timestamp with time zone NOT NULL);                                                                                                                                               |
| CREATE TABLE family_profiles (guardian_relationship text, id uuid NOT NULL, updated_at timestamp with time zone NOT NULL, guardian_occupation text, father_occupation text, father_name text, mother_name text, mother_occupation text, guardian_name text); |
| CREATE TABLE profiles (created_at timestamp with time zone NOT NULL, id uuid NOT NULL, last_name text NOT NULL, role text NOT NULL, first_name text NOT NULL);                                                                                               |
| CREATE TABLE schools (created_at timestamp with time zone NOT NULL, type text NOT NULL, id bigint NOT NULL, name text NOT NULL);                                                                                                                             |
| CREATE TABLE student_details (updated_at timestamp with time zone NOT NULL, contact_number text NOT NULL, year_level text NOT NULL, school_id bigint NOT NULL, barangay_id bigint NOT NULL, birth_date date NOT NULL, id uuid NOT NULL);                     |