-- ========================================================
-- 1. DATABASE STRUCTURE (TABLES)
-- ========================================================

CREATE TABLE IF NOT EXISTS barangays (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name text UNIQUE NOT NULL, 
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS schools (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name text UNIQUE NOT NULL, 
    type text NOT NULL, 
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profiles (
    id uuid PRIMARY KEY, 
    first_name text NOT NULL, 
    last_name text NOT NULL, 
    role text NOT NULL, 
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS student_details (
    id uuid PRIMARY KEY, 
    birth_date date NOT NULL, 
    contact_number text NOT NULL, 
    barangay_id int8 REFERENCES barangays(id), 
    school_id int8 REFERENCES schools(id), 
    year_level text NOT NULL, 
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assistance_programs (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    title text NOT NULL, 
    description text, 
    academic_year text NOT NULL, 
    semester text NOT NULL, 
    is_open bool NOT NULL DEFAULT true, 
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS applications (
    id uuid PRIMARY KEY, 
    student_id uuid REFERENCES profiles(id), 
    status text NOT NULL, 
    remarks text, 
    applied_at timestamptz DEFAULT now(), 
    ticket_number text UNIQUE, 
    claim_status text, 
    claimed_at timestamptz
);

CREATE TABLE IF NOT EXISTS application_documents (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    application_id uuid REFERENCES applications(id), 
    document_type text NOT NULL, 
    file_path text NOT NULL, 
    is_verified bool NOT NULL DEFAULT false, 
    uploaded_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS family_profiles (
    id uuid PRIMARY KEY, 
    father_name text, 
    father_occupation text, 
    mother_name text, 
    mother_occupation text, 
    guardian_name text, 
    guardian_relationship text, 
    guardian_occupation text, 
    updated_at timestamptz DEFAULT now()
);

-- ========================================================
-- 2. DATABASE RECORDS (DATA COPIED FROM SUPABASE SEED)
-- ========================================================

-- (Optional: If you want to insert hardcoded data rows here, 
-- you can add them below using the standard format:
-- INSERT INTO barangays (name) VALUES ('Sample Barangay') ON CONFLICT DO NOTHING;
-- If you just want the full structure ready for your repository, this file is fully ready.)